### ISSUE TITLE
Why not put block data in a relational database?

### ISSUE THREAD

**Issue by jiangxjcn** [blockchain-etl/ethereum-etl-neo4j#2]
The block does not appear as a node of the relationship.

**Comment by medvedev1088** [comment]
That's a good point. Either the block data shouldn't be in the Neo4j database or if it's needed for graph queries the schema will need to be changed so that transactions, traces, and token_transfers are nodes themselves, so they can be linked to blocks. But this will complicate the schema substantially.

There is another repo for Postgres ETL https://github.com/blockchain-etl/ethereum-etl-postgres.

**Comment by jiangxjcn** [comment]
I wonder whether it is better to use relational database and graph database at the same time.
For example, storage block data with mysql, storage address ，transaction ，token_transfer , trace with neo4j.

**Comment by medvedev1088** [comment]
That's also an option. The concrete setup depends on the particular use case.

**Comment by jiangxjcn** [comment]
Thanks very much.
The ethereumetl is really useful.
